[package]
name = "process-viewer"
version = "0.1.0"
authors = ["Jonathan E. Magen <yonkeltron@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5"
nix = "0.19"
paris = "1.5"
procfs = "0.9"
